// <auto-generated />
using System;
using FCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCanteen.Data.Migrations
{
    [DbContext(typeof(FCanteenContext))]
    [Migration("20260923223705_Lab03AddStaff")]
    partial class Lab03AddStaff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCanteen.Data.Entities.DailySettlement", b =>
                {
                    b.Property<int>("DailySettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailySettlementId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("CalculationTimeMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.HasKey("DailySettlementId");

                    b.ToTable("DailySettlements");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("DeviceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceLogId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DeviceLogId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<decimal>("AlertThreshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MenuItemId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            IsAvailable = true,
                            Name = "Cơm gà",
                            Price = 35000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            MenuItemId = 2,
                            IsAvailable = true,
                            Name = "Cơm sườn",
                            Price = 40000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            MenuItemId = 3,
                            IsAvailable = true,
                            Name = "Cơm bò xào",
                            Price = 45000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            MenuItemId = 4,
                            IsAvailable = true,
                            Name = "Mì xào bò",
                            Price = 40000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            MenuItemId = 5,
                            IsAvailable = true,
                            Name = "Mì xào trứng",
                            Price = 30000m,
                            Unit = "Phần"
                        },
                        new
                        {
                            MenuItemId = 6,
                            IsAvailable = true,
                            Name = "Bún bò",
                            Price = 40000m,
                            Unit = "Tô"
                        },
                        new
                        {
                            MenuItemId = 7,
                            IsAvailable = true,
                            Name = "Phở bò",
                            Price = 45000m,
                            Unit = "Tô"
                        },
                        new
                        {
                            MenuItemId = 8,
                            IsAvailable = true,
                            Name = "Bánh mì thịt",
                            Price = 25000m,
                            Unit = "Ổ"
                        },
                        new
                        {
                            MenuItemId = 9,
                            IsAvailable = true,
                            Name = "Bánh mì trứng",
                            Price = 20000m,
                            Unit = "Ổ"
                        },
                        new
                        {
                            MenuItemId = 10,
                            IsAvailable = true,
                            Name = "Xôi gà",
                            Price = 30000m,
                            Unit = "Hộp"
                        },
                        new
                        {
                            MenuItemId = 11,
                            IsAvailable = true,
                            Name = "Nước suối",
                            Price = 10000m,
                            Unit = "Chai"
                        },
                        new
                        {
                            MenuItemId = 12,
                            IsAvailable = true,
                            Name = "Coca Cola",
                            Price = 15000m,
                            Unit = "Lon"
                        },
                        new
                        {
                            MenuItemId = 13,
                            IsAvailable = true,
                            Name = "Pepsi",
                            Price = 15000m,
                            Unit = "Lon"
                        },
                        new
                        {
                            MenuItemId = 14,
                            IsAvailable = true,
                            Name = "Trà đào",
                            Price = 20000m,
                            Unit = "Ly"
                        },
                        new
                        {
                            MenuItemId = 15,
                            IsAvailable = true,
                            Name = "Cà phê sữa",
                            Price = 20000m,
                            Unit = "Ly"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<int>("OrderTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderTicketId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BR01");

                    b.Property<string>("CounterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderTicketId");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StaffId");

                    b.HasIndex("StaffCode")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("TicketLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketLineId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketLineId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("TicketLines")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Navigation("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
